Debugger:
  Matrix:
    Enabled:
      False
    Room_id:
      ""
  Testmode:
    Enabled:
      False
    Allowed_ip_list:
      - 1.1.1.1
    Main_domain:
      main_domain
    Second_domain:
      second_domain
    Register_domain:
      register_domain
    Joining_domain:
      joining_domain
  Maintance:
    Enabled:
      False
    Allowed_ip_list:
      - 1.1.1.1
Matrix:
  Server:
    Url:
      matrix_url # Adress of matrix instance
  User:
    Access_token:
      matrix_access # Matrix token
Nextcloud:
  Server:
    Url:
      nextcloud_url # Adress of nextcloud instance
  User:
    Username:
      nextcloud_username # Nextcloud admin username
    Password:
      nextcloud_password # Nextcloud admin password
Website:
  Domains:
    Main_domain:
      main_domain
    Second_domain:
      second_domain
    Register_domain:
      register_domain
    Joining_domain:
      joining_domain
  Rooms:
    Notification:
      ""
    2fa_room:
      name:
        ""
    WG: # List of roomids that user is invited when joining
      - ""
  Paths:
    Upload:
      ""
    DB:
      ""
  Secrets:
    Admin:
      2FA:
        ""
    Account:
      Creating:
        Enabled:
          False
        Token:
          token
        Server:
          ""
        Ending:
          ""
        Secret:
          ""
    SSL:
      privkey:
        ''
      pubkey:
        ''
        
